<?php

use App\Http\Controllers\Api\AdminUserController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\CategoryController;
use App\Http\Controllers\Api\CustomerPortalController;
use App\Http\Controllers\Api\OrderRequestController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\SiteContactController;
use App\Http\Controllers\Api\StaffController;
use App\Http\Controllers\Api\SupportCenterController;
use App\Http\Controllers\Api\WithdrawalController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::post('/auth/register', [AuthController::class, 'register']);
    Route::post('/auth/login', [AuthController::class, 'login']);
    Route::get('/site/contact', [SiteContactController::class, 'show']);
    Route::get('/categories', [CategoryController::class, 'publicIndex']);
    Route::get('/products', [ProductController::class, 'index']);
    Route::get('/products/{product:slug}', [ProductController::class, 'show']);

    Route::middleware(['auth:sanctum', 'active'])->group(function () {
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::get('/auth/me', [AuthController::class, 'me']);
        Route::get('/order-requests', [OrderRequestController::class, 'index']);
        Route::post('/order-requests', [OrderRequestController::class, 'store']);
        Route::get('/order-requests/{orderRequest}', [OrderRequestController::class, 'show']);
        Route::get('/portal/summary', [CustomerPortalController::class, 'summary']);
        Route::patch('/portal/profile', [CustomerPortalController::class, 'updateProfile']);
        Route::patch('/portal/account', [CustomerPortalController::class, 'completeAccount']);
        Route::patch('/portal/password', [CustomerPortalController::class, 'changePassword']);
        Route::get('/portal/orders', [CustomerPortalController::class, 'orders']);
        Route::get('/portal/support', [SupportCenterController::class, 'customerShow']);
        Route::post('/portal/support/messages', [SupportCenterController::class, 'customerSend'])->middleware('throttle:30,1');
        Route::post('/portal/support/read', [SupportCenterController::class, 'customerRead']);
        Route::get('/portal/support/unread-count', [SupportCenterController::class, 'customerUnread']);
        Route::post('/support/realtime/auth', [SupportCenterController::class, 'authorizeRealtime'])->middleware('throttle:120,1');
        Route::get('/portal/orders/{order}', [CustomerPortalController::class, 'showOrder']);
        Route::post('/portal/orders/{order}/wallet-payment', [CustomerPortalController::class, 'payWithWallet']);
        Route::get('/withdrawals', [WithdrawalController::class, 'index']);
        Route::post('/withdrawals', [WithdrawalController::class, 'store']);
        Route::post('/withdrawals/{withdrawalRequest}/cancel', [WithdrawalController::class, 'cancel']);
        Route::get('/withdrawals/{withdrawalRequest}', [WithdrawalController::class, 'show']);

        Route::prefix('staff')->group(function () {
            Route::get('/support', [SupportCenterController::class, 'staffIndex']);
            Route::get('/support/unread-count', [SupportCenterController::class, 'staffUnread']);
            Route::get('/support/customers/{customer}', [SupportCenterController::class, 'staffCustomerShow']);
            Route::post('/support/customers/{customer}/messages', [SupportCenterController::class, 'staffCustomerSend'])->middleware('throttle:30,1');
            Route::get('/support/{conversation}', [SupportCenterController::class, 'staffShow']);
            Route::post('/support/{conversation}/messages', [SupportCenterController::class, 'staffSend'])->middleware('throttle:30,1');
            Route::post('/support/{conversation}/read', [SupportCenterController::class, 'staffRead']);
            Route::get('/users', [AdminUserController::class, 'index']);
            Route::post('/users', [AdminUserController::class, 'store']);
            Route::patch('/users/{user}', [AdminUserController::class, 'update']);
            Route::patch('/users/{user}/status', [AdminUserController::class, 'updateStatus']);
            Route::get('/dashboard', [StaffController::class, 'dashboard']);
            Route::patch('/password', [StaffController::class, 'changePassword']);
            Route::get('/customers', [StaffController::class, 'customers']);
            Route::get('/customers/{customer}', [StaffController::class, 'showCustomer']);
            Route::patch('/customers/{customer}/status', [StaffController::class, 'updateCustomerStatus']);
            Route::patch('/customers/{customer}/password', [StaffController::class, 'resetCustomerPassword']);
            Route::patch('/site/contact', [SiteContactController::class, 'update']);
            Route::get('/order-requests', [StaffController::class, 'requests']);
            Route::get('/order-requests/{orderRequest}', [StaffController::class, 'showRequest']);
            Route::post('/order-requests/{orderRequest}/finalize', [StaffController::class, 'finalize']);
            Route::post('/order-requests/{orderRequest}/close', [StaffController::class, 'closeRequest']);
            Route::get('/orders', [StaffController::class, 'orders']);
            Route::get('/orders/{order}', [StaffController::class, 'showOrder']);
            Route::patch('/orders/{order}/status', [StaffController::class, 'updateStatus']);
            Route::patch('/orders/{order}/payment', [StaffController::class, 'markPaid']);
            Route::post('/orders/{order}/cashback', [StaffController::class, 'addCashback']);
            Route::post('/orders/{order}/wallet-redemption', [StaffController::class, 'redeemWallet']);
            Route::get('/products', [ProductController::class, 'staffIndex']);
            Route::post('/products', [ProductController::class, 'store']);
            Route::patch('/products/{product}', [ProductController::class, 'update']);
            Route::delete('/products/{product}', [ProductController::class, 'destroy']);
            Route::get('/categories', [CategoryController::class, 'index']);
            Route::post('/categories/{category}/image', [CategoryController::class, 'updateImage']);
            Route::delete('/categories/{category}/image', [CategoryController::class, 'removeImage']);
            Route::post('/categories', [CategoryController::class, 'store']);
            Route::patch('/categories/{category}', [CategoryController::class, 'update']);
            Route::delete('/categories/{category}', [CategoryController::class, 'destroy']);
            Route::get('/withdrawals', [WithdrawalController::class, 'staffIndex']);
            Route::post('/withdrawals/{withdrawalRequest}/review', [WithdrawalController::class, 'review']);
            Route::post('/withdrawals/{withdrawalRequest}/approve', [WithdrawalController::class, 'approve']);
            Route::post('/withdrawals/{withdrawalRequest}/reject', [WithdrawalController::class, 'reject']);
            Route::post('/withdrawals/{withdrawalRequest}/process', [WithdrawalController::class, 'process']);
        });
    });
});
